name: Gradle Dependency Submission
on:
  push:
    branches: [ "main" ]

jobs:
  gradle-action-detection:
    runs-on: ubuntu-latest
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: set up JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
          

