---
name: Automatically Translate Android App

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]
    paths:
    - "**/strings.xml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Run locally with "act -j translateAndroid"
  translateAndroid:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Translate strings.xml to supported languages
        uses: ashishb/android-auto-translate@master

      - name: Commit Translations
        run: |
          git config --global user.name 'Translation Bot'
          git config --global user.email 'gyund@users.noreply.github.com'
          git commit -am "Automated Translation"
          git push
